// SPDX-License-Identifier: AGPL-3.0-only
#pragma once

#include <array>
#include <memory>
#include <string>
#include <vector>

#include "mgstc/engine/composite_timbre.hpp"
#include "mgstc/engine/scc_waveform.hpp"

namespace mgstc::engine {

inline constexpr std::uint32_t kSccMorphAlgorithmVersion = 2;
// Version 1 authored projects are regenerated by the current algorithm without
// rewriting the authored model or changing the persistent schema.
[[nodiscard]] constexpr bool isSupportedSccMorphAlgorithmVersion(
    std::uint32_t version) noexcept {
    return version == 1 || version == kSccMorphAlgorithmVersion;
}
inline constexpr double kSccMorphGammaMax = 8.0;
inline constexpr double kSccMorphGammaMin = 1.0 / kSccMorphGammaMax;

struct SccMorphDescriptors {
    double centroid{}, spread{}, slope{}, odd_even{}, irregularity{}, flatness{};
    double rms{}, dc{}, peak{};
};

struct SccMorphAnalysis {
    // Normalized DFT: DC and Nyquist are real, positive/negative harmonics
    // are conjugates. Positive harmonics are 1..16 (0 is DC).
    std::array<double, 17> magnitude{}, phase{};
    SccMorphDescriptors descriptors;
};

enum class SccMorphCandidate {
    Source, LogHarmonic, AlignedTime, SpectralEnvelope, Blend,
};
inline constexpr std::size_t kSccMorphCandidateCount = 12;

struct SccMorphWaveDiagnostic {
    std::size_t layer_index{};
    std::uint32_t count{};
    double u{};
    SccMorphCandidate candidate{SccMorphCandidate::Source};
    std::array<double, 3> candidate_weights{};
    double pre_quantization_error{}, post_quantization_error{};
    SccMorphDescriptors target{}, result{};
    std::size_t phase_shift{};
    std::uint8_t output_number{};
    bool generated{};
};

struct SccMorphPairResult {
    std::vector<SccWaveform> intermediate;
    std::vector<SccMorphWaveDiagnostic> diagnostics;
};

// Opt-in, non-audio diagnostic snapshots from the actual generator. Ordinary
// generation does not allocate or retain these float/candidate traces.
struct SccMorphConnectionTrace {
    double phase_wave{}, rms{}, harmonic{}, spectral_shape{}, descriptor{};
    double distance{}, dt{}, du{}, reverse{}, cost{};
};

struct SccMorphCandidateTrace {
    SccMorphCandidate method{SccMorphCandidate::Source};
    std::array<double, 3> weights{};
    std::array<double, 32> reconstructed{}, corrected{}, fitted{};
    SccWaveform quantized{};
    double pre_quantization_error{}, post_quantization_error{};
    double cumulative_cost{};
    std::size_t predecessor{};
    // Incoming connections in candidate index order. At the first position
    // every entry represents the source endpoint.
    std::array<SccMorphConnectionTrace, kSccMorphCandidateCount> incoming{};
};

struct SccMorphStepTrace {
    double t{}, u{};
    SccMorphDescriptors target{};
    std::array<double, 32> target_shape{};
    // The log target before and after its RMS gain normalization, the
    // additional envelope/residual candidate, and unit complex guide angles.
    std::array<double, 17> raw_log_magnitude{}, target_magnitude{};
    std::array<double, 17> advanced_magnitude{}, guide_phase{};
    std::array<SccMorphCandidateTrace, kSccMorphCandidateCount> candidates;
    std::size_t selected_candidate{};
    SccWaveform selected_pre_local{}, selected_post_local{};
    double selected_pre_local_error{}, selected_post_local_error{};
};

struct SccMorphPairTrace {
    SccWaveform first{}, second{}, aligned_second{};
    std::size_t alignment_shift{};
    SccMorphAnalysis first_analysis{}, second_analysis{};
    double epsilon{}, silence{}, trajectory_cost{};
    std::array<SccMorphConnectionTrace, kSccMorphCandidateCount> terminal{};
    std::vector<SccMorphStepTrace> steps;
};

struct SccMorphChannelAllocation {
    std::size_t layer_index{};
    std::uint8_t start{}, count{};
    bool manual{};
};

struct SccMorphCompileResult {
    CompositeTimbre timbre;
    bool valid{true};
    std::string error;
    // Counts only byte-distinct derived waveforms. Capacity excludes source
    // slots already occupied in the selected 0..31 / 16..31 range.
    std::size_t used{}, capacity{}, required{};
    std::vector<SccMorphWaveDiagnostic> diagnostics;
    std::vector<SccMorphChannelAllocation> channel_allocations;
};

[[nodiscard]] double morphPosition(double time, double gamma) noexcept;
[[nodiscard]] SccMorphAnalysis analyzeSccMorphWaveform(const SccWaveform& wave);
[[nodiscard]] double sccMorphTransitionCost(const SccWaveform& first,
                                          const SccWaveform& second) noexcept;
[[nodiscard]] SccMorphPairResult generateSccMorph(
    const SccWaveform& first, const SccWaveform& second,
    std::uint8_t intermediate_count, double gamma = 1.0);
// Uses the same operations, policy and candidate decisions as generateSccMorph;
// trace is replaced on each call and is never part of a persistent model/cache.
[[nodiscard]] SccMorphPairResult generateSccMorphTraced(
    const SccWaveform& first, const SccWaveform& second,
    std::uint8_t intermediate_count, double gamma, SccMorphPairTrace& trace);
// Diagnostic equivalent of compileSccMorph's playback-time scoring. Counts
// include both endpoints and must be strictly increasing (N + 2 entries).
// Authored interpolation t/u stay at i/(N + 1), independent of rounded counts.
[[nodiscard]] SccMorphPairResult generateSccMorphTraced(
    const SccWaveform& first, const SccWaveform& second,
    std::uint8_t intermediate_count, double gamma, SccMorphPairTrace& trace,
    const std::vector<std::uint32_t>& counts);
// Exact 32-state dynamic programming on quantized waves. Endpoints remain
// byte-identical when fixed; all other nodes may be circularly shifted.
[[nodiscard]] std::vector<std::size_t> optimizeSccMorphBlockPhases(
    std::vector<SccWaveform>& waves, bool fixed_start, bool fixed_end);
// Non-audio-thread API. Keeps authored sources/events intact and materializes
// the derived cache into a separate CompositeTimbre for existing consumers.
[[nodiscard]] SccMorphCompileResult compileSccMorph(const CompositeTimbre& input);
// Bounded one-entry cache per preparation thread; exact model equality is the
// invalidation key, including source snapshots and output allocation settings.
[[nodiscard]] std::shared_ptr<const SccMorphCompileResult> compileSccMorphCached(
    const CompositeTimbre& input);

} // namespace mgstc::engine
